services:
  mysql:
    image: mysql:8.0
    container_name: sae_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sae_db
      MYSQL_USER: sae_user
      MYSQL_PASSWORD: sae_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: